import { Injectable } from '@angular/core';
import * as jsPDF from 'jspdf';

@Injectable({
  providedIn: 'root'
})
export class BundlePdfTronBuilderService {

  constructor() { }

  generateCover(): jsPDF {
    const doc: jsPDF = new jsPDF();

    // For Downloaded file it works, but if it is rendered in PdfTron document - link is not working
    doc.textWithLink('Link', 30, 30, { url: 'https://www.google.com/' });


    // Should link to Page - generated by PdfTron
    // I was thinking about - jsPdf create a Link
    // but PdfTron create an anchor somehow - and be clicking it will match (find an anchor)
    // doc.textWithLink('Link', 50, 50, { url: '#page=3' });

    doc.save('Link test');


    return doc;
  }



}
